### ISSUE TITLE
Put semicolons at the end of the statements

### ISSUE THREAD

**Issue by igui** [GonzaloRizzo/urudolar-telegram-bot#1]
It can help to prevent JS errors on the future

**Comment by GonzaloRizzo** [comment]
No semicolons – [It's](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) [fine](http://inimino.org/~inimino/blog/javascript_semicolons). [Really!](https://www.youtube.com/watch?v=gsfbh17Ax9I)
