### ISSUE TITLE
Delete config folder

### ISSUE THREAD

**Issue by pablomujica** [GonzaloRizzo/urudolar-telegram-bot#2]
Podes borrar la config folder, tiene un archivo de ejemplo que esta al dope y gente se puede confundir con verdaderos configs

**Comment by GonzaloRizzo** [comment]
I can't delete this file because it's a template that explains how to create your own config file. It shouldn't be confused with a real config since it clearly says that it's an example in its name

**Comment by GonzaloRizzo** [comment]
Even though, I have been thinking in creating a library that prompts for the missing config parameters when a config file isn't found so I may delete it in the future

**Comment by pablomujica** [comment]
it was my error. i closed the issue, once a started reading your code i found that i was mistaken! great work!
